# Basic Site Info
title: Jekyll News Theme
description: "Built with Morpheus636's Jekyll-News Theme"
author: Morpheus636

# Site Flag
flag:
  show: true
  path: /assets/flag.png

# Comments
disqus:
  enabled: true
  shortname: jekyll-news-demo  #REPLACEME

# Analytics
google_analytics: G-GRV8PX7ZN1

# Ads
adsense:
  enabled: true
  data-ad-client: ca-pub-9280169319319657  #REPLACEME

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  staff:
    output: true
    permalink: /about/staff/:title

# Build settings
markdown: kramdown
remote_theme: morpheus636/jekyll-news
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
